name: dartsrctrl
description: A Dart source code parser and indexer for Sourcetrail
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  args: ^2.3.1
  path: ^1.8.2
  yaml: ^3.1.1
  collection: ^1.16.0
  logging: ^1.1.0
  pub_semver: ^2.1.3
  package_config: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
